import {neutralAdjustments,collagePositions} from './photo-core.js';
const $=id=>document.getElementById(id);
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
function surface(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
function copy(source){const c=surface(source.width,source.height);c.getContext('2d').drawImage(source,0,0);return c;}
function alphaOf(canvas){const rgba=canvas.getContext('2d',{willReadFrequently:true}).getImageData(0,0,canvas.width,canvas.height).data;const a=new Uint8Array(canvas.width*canvas.height);for(let i=0;i<a.length;i++)a[i]=rgba[i*4+3];return a;}
function setAlpha(canvas,alpha){const rgba=new Uint8ClampedArray(alpha.length*4);for(let i=0;i<alpha.length;i++){rgba[i*4]=rgba[i*4+1]=rgba[i*4+2]=255;rgba[i*4+3]=alpha[i];}canvas.getContext('2d').putImageData(new ImageData(rgba,canvas.width,canvas.height),0,0);}
export function createPhotoStudio({getState,working,original,maskCanvas,overlayCanvas,render,sync:syncApp,setView,setBusy,setProgress,toast,clearSelection,resizeDocument}){
  let layers=[],selected=null,pane='repair',cutout='background',background='transparent',nextId=1,history=[],polygon=[],drag=null,worker=null,jobId=1,epoch=0;
  const jobs=new Map(),timers=new Map();
  const current=()=>layers.find(l=>l.id===selected);
  const ready=()=>getState().mode==='image'&&layers.length>0;
  const blocked=()=>getState().busy||getState().loading;
  const pending=()=>layers.some(l=>l.pending);
  const canCompare=()=>layers.length===1&&layers[0].isOriginal&&layers[0].x===0&&layers[0].y===0&&layers[0].scale===1&&working.width===original.width&&working.height===original.height&&background==='transparent';
  function createLayer(source,name){const color=copy(source),mask=surface(source.width,source.height),view=copy(source);const c=mask.getContext('2d');c.fillStyle='white';c.fillRect(0,0,mask.width,mask.height);return{id:nextId++,name,source:copy(source),color,mask,view,x:0,y:0,scale:1,opacity:1,adjustments:neutralAdjustments(),applied:neutralAdjustments(),revision:0,pending:false};}
  function rebuild(l){const c=l.view.getContext('2d');c.clearRect(0,0,l.view.width,l.view.height);c.drawImage(l.color,0,0);c.save();c.globalCompositeOperation='destination-in';c.drawImage(l.mask,0,0);c.restore();}
  function compose(changed=true){if(!layers.length)return;const c=working.getContext('2d');c.clearRect(0,0,working.width,working.height);if(background!=='transparent'){c.fillStyle=background;c.fillRect(0,0,working.width,working.height);}for(const l of layers){c.save();c.globalAlpha=l.opacity;c.drawImage(l.view,l.x,l.y,l.view.width*l.scale,l.view.height*l.scale);c.restore();}if(changed)getState().result=true;render();syncApp();}
  function mark(){if(getState().compare)setView(false);compose();}
  function connectWorker(){if(worker)return;worker=new Worker('/photo-worker.js',{type:'module'});worker.onmessage=({data})=>{const j=jobs.get(data.id);if(!j)return;jobs.delete(data.id);clearTimeout(j.timeout);data.error?j.reject(new Error(data.error)):j.resolve(data);};worker.onerror=()=>{stopWorker('图像处理失败，请重试或缩小照片。');};}
  function stopWorker(message='处理已取消。'){worker?.terminate();worker=null;for(const j of jobs.values()){clearTimeout(j.timeout);j.reject(new Error(message));}jobs.clear();}
  function run(data,transfer=[]){connectWorker();return new Promise((resolve,reject)=>{const id=jobId++;const timeout=setTimeout(()=>{stopWorker('处理超时，请尝试更小的照片。');},30000);jobs.set(id,{resolve,reject,timeout});try{worker.postMessage({id,...data},transfer);}catch(e){clearTimeout(timeout);jobs.delete(id);reject(e);}});}
  function renderLayers(){const list=$('layer-list');list.replaceChildren();for(const l of layers){const b=document.createElement('button');b.className='layer-card';b.dataset.layer=String(l.id);b.title=l.name;b.setAttribute('aria-pressed',String(l.id===selected));const thumb=surface(48,40),c=thumb.getContext('2d'),s=Math.min(48/l.view.width,40/l.view.height);c.drawImage(l.view,(48-l.view.width*s)/2,(40-l.view.height*s)/2,l.view.width*s,l.view.height*s);const text=document.createElement('span');text.textContent=l.name;b.append(thumb,text);b.addEventListener('click',()=>selectLayer(l.id));list.append(b);}sync();}
  function updateControls(){const l=current();$('active-layer-name').textContent=l?.name||'请先选择照片';for(const input of document.querySelectorAll('[data-adjust]')){const value=l?.adjustments[input.dataset.adjust]||0;input.value=value;$('value-'+input.dataset.adjust).textContent=value>0?'+'+value:String(value);}if(l){$('layer-scale').max=String(Math.max(300,Math.ceil(l.scale*100)));$('layer-scale').value=String(l.scale*100);$('value-scale').textContent=Math.round(l.scale*100)+'%';$('layer-opacity').value=String(l.opacity*100);$('value-opacity').textContent=Math.round(l.opacity*100)+'%';$('layer-x').value=String(Math.round(l.x));$('layer-y').value=String(Math.round(l.y));}$('photo-background').value=background;}
  function sync(){const s=getState(),image=s.mode==='image',available=ready(),off=blocked()||!available;const l=current();$('photo-toolbar').hidden=!image;$('photo-layers').hidden=!image||!layers.length;$('photo-tools').hidden=!image||pane==='repair';$('repair-selection-tools').hidden=$('repair-process-tools').hidden=image&&pane!=='repair';$('panel-tool-title').textContent=!image||pane==='repair'?'修复工具':{tone:'色彩与清晰度',compose:'照片合成',cutout:'抠图修边'}[pane];$('photo-status').textContent=image?(pending()?'正在调色…':layers.length?`${layers.length} 个图层`:'LOCAL STUDIO'):'VIDEO STUDIO';$('download-label').textContent=image?'下载照片':'下载修复结果';$('reset').textContent=image?'重置全部编辑':'恢复原始画面';$('add-photo').disabled=off||layers.length>=8;$('layer-count').textContent=layers.length+' / 8';
    document.querySelectorAll('[data-photo-pane]').forEach(b=>{b.disabled=off;b.classList.toggle('active',b.dataset.photoPane===pane);b.setAttribute('aria-pressed',String(b.dataset.photoPane===pane));});
    document.querySelectorAll('.photo-pane').forEach(p=>p.hidden=p.id!=='pane-'+pane);
    document.querySelectorAll('#photo-tools button,#photo-tools input,#photo-tools select,.layer-card').forEach(el=>el.disabled=off);
    document.querySelectorAll('.layer-card').forEach(b=>{b.classList.toggle('active',Number(b.dataset.layer)===selected);b.setAttribute('aria-pressed',String(Number(b.dataset.layer)===selected));});
    $('layer-delete').disabled=off||layers.length<2;$('layer-back').disabled=off||layers.indexOf(l)===0;$('layer-front').disabled=off||layers.indexOf(l)===layers.length-1;document.querySelectorAll('[data-layout]').forEach(b=>b.disabled=off||layers.length<2);
    $('finish-polygon').disabled=off||polygon.length<3;$('cancel-polygon').disabled=off||!polygon.length;$('undo-cutout').disabled=off||!history.some(h=>h.id===selected);$('download-cutout').disabled=off||Boolean(l?.pending);
    if(image){$('download').disabled=off||pending()||!s.result;$('process').disabled=$('process').disabled||pending();$('view-toggle').hidden=!s.result||!canCompare();$('compare-view').disabled=blocked()||pending()||!canCompare();if(available)$('canvas-hint').textContent=pane==='repair'?'修复当前图层 · 涂抹或框选需要擦除的区域':pane==='tone'?'在右侧调整当前图层 · 点击下方图层切换编辑对象':pane==='compose'?'拖动照片移动 · 右下角等比缩放 · 方向键微调':{background:'点击背景去除相连的相近颜色',polygon:`沿主体点击圈选 · 已标记 ${polygon.length} 个点 · Enter 完成`,erase:'涂抹去掉多余部分，可撤销这次修边',restore:'涂抹恢复误删部分，不会修改其他图层'}[cutout];}
    if(image)maskCanvas.style.cursor=pane==='tone'?'default':pane==='compose'?'move':'crosshair';else maskCanvas.style.cursor='crosshair';
  }
  function selectPane(value){if(!['repair','tone','compose','cutout'].includes(value)||blocked()||!ready())return;pane=value;polygon=[];drag=null;clearSelection();setView(false);updateControls();syncApp();drawOverlay();}
  function selectLayer(id){if(blocked()||!layers.some(l=>l.id===id))return;selected=id;polygon=[];clearSelection();setView(false);updateControls();syncApp();drawOverlay();}
  function drawOverlay(){if(getState().mode!=='image')return;const c=overlayCanvas.getContext('2d');c.clearRect(0,0,overlayCanvas.width,overlayCanvas.height);overlayCanvas.style.opacity='1';const l=current();if(!l||getState().compare)return;const k=working.width/(maskCanvas.getBoundingClientRect().width||working.width);c.save();c.strokeStyle='#c7f59b';c.fillStyle='#c7f59b';c.lineWidth=1.5*k;
    if(pane==='compose'){c.setLineDash([6*k,4*k]);c.strokeRect(l.x,l.y,l.view.width*l.scale,l.view.height*l.scale);c.setLineDash([]);const x=l.x+l.view.width*l.scale,y=l.y+l.view.height*l.scale;c.fillRect(x-6*k,y-6*k,12*k,12*k);}
    if(pane==='cutout'&&cutout==='polygon'&&polygon.length){c.beginPath();polygon.forEach((p,i)=>i?c.lineTo(l.x+p.x*l.scale,l.y+p.y*l.scale):c.moveTo(l.x+p.x*l.scale,l.y+p.y*l.scale));if(polygon.length>2)c.closePath();c.fillStyle='#c7f59b22';c.fill();c.stroke();c.fillStyle='#c7f59b';for(const p of polygon){c.beginPath();c.arc(l.x+p.x*l.scale,l.y+p.y*l.scale,3*k,0,Math.PI*2);c.fill();}}c.restore();
  }
  function clear(){epoch++;for(const t of timers.values())clearTimeout(t);timers.clear();stopWorker();layers=[];selected=null;history=[];polygon=[];drag=null;pane='repair';background='transparent';$('layer-list').replaceChildren();overlayCanvas.style.opacity='.42';}
  function init(source,name){layers=[createLayer(source,name)];layers[0].isOriginal=true;selected=layers[0].id;renderLayers();updateControls();}
  async function applyAdjust(l){clearTimeout(timers.get(l.id));timers.delete(l.id);const rev=l.revision,token=epoch,settings={...l.adjustments};l.pending=true;syncApp();try{const rgba=l.source.getContext('2d').getImageData(0,0,l.source.width,l.source.height).data;const result=await run({kind:'adjust',pixels:rgba.buffer,width:l.source.width,height:l.source.height,settings},[rgba.buffer]);if(token!==epoch||rev!==l.revision||!layers.includes(l))return;l.color.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(result.pixels),l.source.width,l.source.height),0,0);l.applied=settings;l.pending=false;rebuild(l);mark();renderLayers();return true;}catch(e){if(token===epoch&&rev===l.revision&&layers.includes(l)){l.pending=false;l.adjustments={...l.applied};if(l.id===selected)updateControls();syncApp();toast(e.message);}return false;}}
  function queueAdjust(l){l.revision++;l.pending=true;clearTimeout(timers.get(l.id));timers.set(l.id,setTimeout(()=>applyAdjust(l),350));syncApp();}
  async function decode(file){if(!/\.(jpe?g|png|webp)$/i.test(file.name)&&!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('只能添加 JPG、PNG、WebP 照片。');if(file.size>25*1024*1024)throw new Error('每张照片不能超过 25 MB。');const url=URL.createObjectURL(file);try{const im=new Image();await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('照片读取超时。')),20000);im.onload=()=>{clearTimeout(timeout);resolve();};im.onerror=()=>{clearTimeout(timeout);reject(new Error('无法读取照片，请检查格式。'));};im.src=url;});if(!im.naturalWidth||!im.naturalHeight||im.naturalWidth*im.naturalHeight>30000000)throw new Error('照片需小于 3000 万像素。');const remaining=16000000-layers.reduce((n,l)=>n+l.source.width*l.source.height,0);if(remaining<150000)throw new Error('当前合成已达到处理容量，请先删除部分图层。');const scale=Math.min(1,1600/Math.max(im.naturalWidth,im.naturalHeight),Math.sqrt(remaining/(im.naturalWidth*im.naturalHeight)));const out=surface(Math.max(1,Math.round(im.naturalWidth*scale)),Math.max(1,Math.round(im.naturalHeight*scale)));out.getContext('2d').drawImage(im,0,0,out.width,out.height);return out;}finally{URL.revokeObjectURL(url);}}
  async function addPhotos(files,{arrange=false}={}){if(!ready()||blocked())return;setView(false);const chosen=[...files];if(!chosen.length)return;setBusy(true,'正在添加照片…','照片将在本地读取，添加为独立图层。');const token=epoch;let added=0,cancelled=false;getState().cancelImage=()=>{cancelled=true;};try{for(const file of chosen){if(cancelled)break;if(layers.length>=8){toast('最多添加 8 个图层，已保留前面成功读取的照片。');break;}try{const source=await decode(file);if(token!==epoch||cancelled)break;const l=createLayer(source,file.name);l.scale=Math.min(1,working.width*.72/l.source.width,working.height*.72/l.source.height);l.x=(working.width-l.source.width*l.scale)/2;l.y=(working.height-l.source.height*l.scale)/2;layers.push(l);selected=l.id;added++;setProgress(added/chosen.length*100);}catch(e){toast(file.name+'：'+e.message);}}}finally{getState().cancelImage=null;setBusy(false);if(added&&token===epoch){pane='compose';polygon=[];clearSelection();if(arrange&&layers.length>1)arrangeLayers('grid');else compose();renderLayers();updateControls();syncApp();}if(cancelled)toast('已停止添加，成功读取的照片已保留。');}}
  function documentSize(w,h){resizeDocument(w,h);polygon=[];clearSelection();}
  function arrangeLayers(kind){if(blocked()||layers.length<2)return;setView(false);const layout=collagePositions(layers.map(l=>({id:l.id,width:l.source.width,height:l.source.height})),kind);documentSize(layout.width,layout.height);for(const p of layout.placements)Object.assign(layers.find(l=>l.id===p.id),p);mark();updateControls();}
  function moveLayer(delta){const l=current(),i=layers.indexOf(l),j=i+delta;if(blocked()||j<0||j>=layers.length)return;[layers[i],layers[j]]=[layers[j],layers[i]];mark();renderLayers();}
  function setBackground(){const l=current();if(blocked()||!l)return;setView(false);const sx=l.source.width/working.width,sy=l.source.height/working.height;for(const other of layers){other.x*=sx;other.y*=sy;other.scale*=Math.min(sx,sy);}layers=layers.filter(x=>x!==l);layers.unshift(l);l.x=0;l.y=0;l.scale=1;l.opacity=1;documentSize(l.source.width,l.source.height);mark();renderLayers();updateControls();toast('已将当前照片设为底层背景，并适配画布尺寸。');}
  function fitLayer(){const l=current();if(blocked()||!l)return;l.scale=Math.min(working.width/l.source.width,working.height/l.source.height,3);l.x=(working.width-l.source.width*l.scale)/2;l.y=(working.height-l.source.height*l.scale)/2;mark();updateControls();}
  function remember(l){const alpha=alphaOf(l.mask);history.push({id:l.id,alpha});while(history.length>6||history.reduce((n,h)=>n+h.alpha.byteLength,0)>32000000)history.shift();}
  function undoCutout(){if(blocked())return;const l=current();for(let i=history.length-1;i>=0;i--){if(history[i].id===l?.id){setAlpha(l.mask,history.splice(i,1)[0].alpha);rebuild(l);polygon=[];mark();renderLayers();return;}}}
  async function maskOperation(kind,options={}){const l=current();if(blocked()||!l)return;const token=epoch;setView(false);setBusy(true,'正在处理抠图…','只修改当前图层，其他照片保持不变。');let cancelled=false;getState().cancelImage=()=>{cancelled=true;stopWorker();};try{const alpha=alphaOf(l.mask),data={kind,width:l.source.width,height:l.source.height,alpha:alpha.buffer,...options},transfer=[alpha.buffer];if(kind==='background'){const rgba=l.source.getContext('2d').getImageData(0,0,l.source.width,l.source.height).data;data.pixels=rgba.buffer;transfer.push(rgba.buffer);}const result=await run(data,transfer);if(cancelled||token!==epoch)return;remember(l);setAlpha(l.mask,new Uint8Array(result.alpha));rebuild(l);polygon=[];compose();renderLayers();if(kind==='background'&&!result.removed)toast('此处已透明，或没有可去除的相连颜色。');}catch(e){if(token===epoch)toast(cancelled?'已取消抠图。':e.message);}finally{getState().cancelImage=null;setBusy(false);}}
  function setCutout(tool){if(blocked())return;cutout=tool;polygon=[];document.querySelectorAll('[data-cutout]').forEach(b=>{const active=b.dataset.cutout===tool;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});$('cutout-hint').textContent={background:'点击要去掉的背景，移除相连的相近颜色。适合纯色或简单背景。',polygon:'沿主体外缘逐点圈选，至少 3 个点。完成后仅保留圈内部分；Enter 完成，Esc 取消。',erase:'在照片上涂抹，擦掉多余背景。下方可以撤销。',restore:'涂抹恢复被误删的部分，按原照片还原。'}[tool];$('tolerance-control').hidden=tool!=='background';$('cutout-brush-control').hidden=!['erase','restore'].includes(tool);$('polygon-controls').hidden=tool!=='polygon';syncApp();drawOverlay();}
  function local(l,p){return{x:(p.x-l.x)/l.scale,y:(p.y-l.y)/l.scale};}
  function inside(l,p){const q=local(l,p);return q.x>=0&&q.y>=0&&q.x<l.source.width&&q.y<l.source.height;}
  function brush(l,a,b){const c=l.mask.getContext('2d');c.save();c.globalCompositeOperation=cutout==='erase'?'destination-out':'source-over';c.fillStyle=c.strokeStyle='white';c.lineWidth=Number($('cutout-brush').value)/l.scale;c.lineCap='round';c.lineJoin='round';c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.beginPath();c.arc(b.x,b.y,c.lineWidth/2,0,Math.PI*2);c.fill();c.restore();rebuild(l);compose();}
  function pointerDown(e,p){if(pane==='repair')return false;if(blocked()||!ready())return true;$('cursor').style.display='none';let l=current();if(pane==='tone')return true;e.preventDefault();
    if(pane==='compose'){const k=working.width/(maskCanvas.getBoundingClientRect().width||working.width);const resize=l&&Math.hypot(p.x-l.x-l.source.width*l.scale,p.y-l.y-l.source.height*l.scale)<17*k;if(!resize){const hit=[...layers].reverse().find(item=>inside(item,p)&&item.opacity>0);if(!hit)return true;selectLayer(hit.id);l=hit;}drag={type:resize?'resize':'move',id:l.id,start:p,x:l.x,y:l.y,scale:l.scale};maskCanvas.setPointerCapture(e.pointerId);}
    else if(l){const q=local(l,p);if(!inside(l,p)){toast('请点击当前图层的照片范围内。');return true;}if(cutout==='background')maskOperation('background',{x:Math.floor(q.x),y:Math.floor(q.y),tolerance:Number($('cutout-tolerance').value)});else if(cutout==='polygon'){polygon.push(q);drawOverlay();syncApp();}else{remember(l);drag={type:'brush',id:l.id,last:q};maskCanvas.setPointerCapture(e.pointerId);brush(l,q,q);}}return true;
  }
  function pointerMove(e,p){if(pane==='repair')return false;$('cursor').style.display='none';if(!drag||blocked())return true;const l=layers.find(item=>item.id===drag.id);if(!l)return true;e.preventDefault();if(drag.type==='move'){l.x=clamp(drag.x+p.x-drag.start.x,-l.source.width*l.scale+10,working.width-10);l.y=clamp(drag.y+p.y-drag.start.y,-l.source.height*l.scale+10,working.height-10);}else if(drag.type==='resize'){const dx=p.x-drag.x,dy=p.y-drag.y;l.scale=clamp((dx*l.source.width+dy*l.source.height)/(l.source.width*l.source.width+l.source.height*l.source.height),.01,Math.max(3,drag.scale*4));}else{const q=local(l,p);brush(l,drag.last,q);drag.last=q;return true;}compose();updateControls();return true;}
  function pointerUp(e){if(pane==='repair')return false;if(drag){if(e.type==='pointercancel'){const l=layers.find(item=>item.id===drag.id);if(l){if(drag.type==='brush')undoCutout();else{l.x=drag.x;l.y=drag.y;l.scale=drag.scale;compose();updateControls();}}}drag=null;renderLayers();}return true;}
  async function downloadCutout(){const l=current();if(blocked()||!l||l.pending)return;try{const blob=await new Promise(resolve=>l.view.toBlob(resolve,'image/png'));if(!blob)throw new Error('无法生成 PNG，请重试。');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(l.name.replace(/\.[^.]+$/,'')||'qingying')+'-抠图.png';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){toast(e.message);}}
  function resetToOriginal(){if(blocked())return;const name=getState().file.name;clear();documentSize(original.width,original.height);init(original,name);getState().result=false;setView(false);compose(false);toast('已恢复第一张原图，调色、抠图和新增图层已重置。');}
  function prepareRepair(){const l=current();if(!l)throw new Error('请先选择照片图层。');const mapped=surface(l.source.width,l.source.height),c=mapped.getContext('2d');c.drawImage(maskCanvas,-l.x/l.scale,-l.y/l.scale,maskCanvas.width/l.scale,maskCanvas.height/l.scale);const marked=alphaOf(mapped),visible=alphaOf(l.mask),pixels=l.source.getContext('2d').getImageData(0,0,l.source.width,l.source.height).data,mask=new Uint8Array(marked.length);let count=0;for(let i=0;i<mask.length;i++){if(marked[i]>20&&visible[i]>20&&pixels[i*4+3]>20){mask[i]=1;count++;}}if(!count)throw new Error('选区不在当前图层的可见部分，请切换到对应的照片图层。');return{id:l.id,width:l.source.width,height:l.source.height,pixels,mask,count};}
  async function applyRepair(id,pixels){const l=layers.find(item=>item.id===id);if(!l)return;const c=l.source.getContext('2d'),before=c.getImageData(0,0,l.source.width,l.source.height);c.putImageData(new ImageData(new Uint8ClampedArray(pixels),l.source.width,l.source.height),0,0);l.revision++;const applied=await applyAdjust(l);if(!applied){c.putImageData(before,0,0);throw new Error('修复预览未完成，已保留上次画面和选区，请重试。');}}
  function keydown(e){if(!ready()||pane==='repair')return false;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(pane==='cutout')undoCutout();return true;}if(e.ctrlKey||e.metaKey||e.altKey)return true;if(pane==='cutout'&&cutout==='polygon'){if(e.key==='Escape'){polygon=[];drawOverlay();syncApp();}if(e.key==='Enter'&&polygon.length>=3){e.preventDefault();maskOperation('polygon',{points:polygon});}}const l=current();if(pane==='compose'&&l&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const n=e.shiftKey?10:1;l.x+=e.key==='ArrowLeft'?-n:e.key==='ArrowRight'?n:0;l.y+=e.key==='ArrowUp'?-n:e.key==='ArrowDown'?n:0;mark();updateControls();}return true;}
  document.querySelectorAll('[data-photo-pane]').forEach(b=>b.addEventListener('click',()=>selectPane(b.dataset.photoPane)));
  $('add-photo').addEventListener('click',()=>{if(!blocked())$('add-photo-input').click();});$('add-photo-input').addEventListener('change',e=>{const files=[...e.target.files];e.target.value='';addPhotos(files);});
  document.querySelectorAll('[data-adjust]').forEach(input=>{input.addEventListener('input',()=>{const l=current();if(blocked()||!l)return;l.adjustments[input.dataset.adjust]=Number(input.value);$('value-'+input.dataset.adjust).textContent=Number(input.value)>0?'+'+input.value:input.value;setView(false);queueAdjust(l);});input.addEventListener('change',()=>{const l=current();if(l&&!blocked())applyAdjust(l);});});
  $('reset-tone').addEventListener('click',()=>{const l=current();if(!l||blocked())return;l.adjustments=neutralAdjustments();l.revision++;updateControls();applyAdjust(l);});
  for(const [id,key] of [['layer-scale','scale'],['layer-opacity','opacity']])$(id).addEventListener('input',e=>{const l=current();if(!l||blocked())return;l[key]=Number(e.target.value)/100;mark();updateControls();});
  for(const key of ['x','y'])$('layer-'+key).addEventListener('change',e=>{const l=current(),v=e.target.valueAsNumber;if(!l||blocked()||!Number.isFinite(v))return;l[key]=clamp(v,-10000,10000);mark();updateControls();});
  $('layer-front').addEventListener('click',()=>moveLayer(1));$('layer-back').addEventListener('click',()=>moveLayer(-1));$('layer-background').addEventListener('click',setBackground);$('layer-fit').addEventListener('click',fitLayer);
  $('layer-delete').addEventListener('click',()=>{if(blocked()||layers.length<2)return;const id=selected;layers=layers.filter(l=>l.id!==id);history=history.filter(h=>h.id!==id);clearTimeout(timers.get(id));timers.delete(id);selected=layers[layers.length-1].id;polygon=[];clearSelection();mark();renderLayers();updateControls();});
  document.querySelectorAll('[data-layout]').forEach(b=>b.addEventListener('click',()=>arrangeLayers(b.dataset.layout)));
  $('photo-background').addEventListener('change',e=>{if(blocked())return;background=e.target.value;mark();});
  document.querySelectorAll('[data-cutout]').forEach(b=>b.addEventListener('click',()=>setCutout(b.dataset.cutout)));
  $('cutout-tolerance').addEventListener('input',e=>$('value-tolerance').textContent=e.target.value);$('cutout-brush').addEventListener('input',e=>$('value-cutout-brush').textContent=e.target.value+' px');
  $('finish-polygon').addEventListener('click',()=>{if(polygon.length>=3)maskOperation('polygon',{points:polygon});});$('cancel-polygon').addEventListener('click',()=>{polygon=[];drawOverlay();syncApp();});$('feather-mask').addEventListener('click',()=>maskOperation('feather'));$('undo-cutout').addEventListener('click',undoCutout);
  $('reset-cutout').addEventListener('click',()=>{const l=current();if(!l||blocked())return;remember(l);const c=l.mask.getContext('2d');c.fillStyle='white';c.fillRect(0,0,l.mask.width,l.mask.height);rebuild(l);polygon=[];mark();renderLayers();});$('download-cutout').addEventListener('click',downloadCutout);
  return{init,clear,sync,drawOverlay,selectPane,addPhotos,prepareRepair,applyRepair,resetToOriginal,pointerDown,pointerMove,pointerUp,keydown,canCompare,pending,get pane(){return pane;},snapshot:()=>({pane,selectedLayer:selected,layers:layers.map(l=>({id:l.id,name:l.name,x:l.x,y:l.y,scale:l.scale,opacity:l.opacity,adjustments:{...l.adjustments}}))})};
}
